EMPTY = 0
FIRST = 1
SECOND = 2

FIELD_COLUMNS = 7
FIELD_ROWS = 6

C_BLACK = (0, 0, 0)
C_EMPTY = (255, 255, 255)
C_FIRST = (237, 28, 36)
C_SECOND = (255, 127, 39)
C_COVER = (63, 72, 204)
C_WIN = (34, 177, 76)

C_LIST = [C_EMPTY, C_FIRST, C_SECOND]

TOKEN_R = 32
TOKEN_D = TOKEN_R * 2
TOKEN_PADDING = 4

TOKEN_CONTENT_SIZE = TOKEN_PADDING * 2 + TOKEN_D
FIELD_WIDTH = FIELD_COLUMNS * TOKEN_CONTENT_SIZE
FIELD_HEIGHT = FIELD_ROWS * TOKEN_CONTENT_SIZE

DRAW_TOKEN_SHIFT = TOKEN_CONTENT_SIZE

S_TURN_WAIT = 1
S_ANIMATION_WAIT = 3
S_END_GAME = 2

TOKEN_FALL_SPEED = TOKEN_CONTENT_SIZE / 8

PANEL_WIDTH = 200
SCREEN_HEIGHT = FIELD_HEIGHT
SCREEN_WIDTH = PANEL_WIDTH + FIELD_WIDTH

TURNS = FIELD_COLUMNS * FIELD_ROWS

STR_ARR_WINNER = [
    "DRAW!",
    "RED PLAYER WON",
    "ORANGE PLAYER WON"
]
